services:
  php:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://sym_user:password@db:3306/my_app_db?serverVersion=8.0
    command: php -S 0.0.0.0:8000 -t public


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: sym_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
